### ISSUE TITLE
Pandas DataFrame to Rules class object for arulesViz

### ISSUE THREAD

**Issue by Mahendra114027** [mhahsler/arulespy#1]
Hi, 
Happy to see a port from R to Python. 

I am new to association rule mining hence I am not sure whether a solution exists.

- My question is, is it possible to convert pandas dataframe with columns (lhs, rhs, support, confidence, lift, conviction) to the Rules class object required for the visualisation of the association rules? 

It would be great if you can point me in the right direction. Thanks!

**Comment by mhahsler** [comment]
Hi,

Yes, but this is not trivial since the items need to be coded as sparse matrices. I will look into this once I find the time.

BTW, how was the installation process? What OS do you use?

-MFH

**Comment by Mahendra114027** [comment]
Hi,

The installation process was smooth. 
I use Ubuntu 22.04.02 LTS. I just followed the steps from README.md and things worked without any issues. 

In the meantime, do you have any workarounds for this problem? 

- MS

**Comment by mhahsler** [comment]
This will be part of arulespy 0.0.3

**Comment by mhahsler** [comment]
This is now available in arulespy_0.1-0.
