### ISSUE TITLE
Interactive Rule Explorer

### ISSUE THREAD

**Issue by Mahendra114027** [mhahsler/arulespy#3]
Hi,

I just wanted to know whether the current port supports [RuleExplorer](https://mhahsler-apps.shinyapps.io/ruleExplorer_demo/)?
It would be great if something like the above demo is available with the current port.

Kind regards,
Mahendra

**Comment by mhahsler** [comment]
RuleExplorer is currently not supported. I am working on getting Shiny to work with Python.

**Comment by mhahsler** [comment]
The latest version (0.1.3) now has support for ruleExplorer. Running Shiny apps via Python is tricky. I hope it works.
